import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Yami UI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[var(--background)] font-[var(--font-sans)] text-[var(--foreground)] flex justify-center">
        <div className="max-w-screen-2xl min-h-screen w-full border border-[var(--border)]">
          {children}
        </div>
      </body>
    </html>
  );
}
